# FGSM Sweep 1

TJ Kim <br/>
1/16/21

Updated <br/>
2/15/21

#### Objective: 
Run FGSM attack on different number of head layers in federated learning and observe performance,


In [1]:
cd '/home/ubuntu/FedAtk/' 

### Load Relevant Libraries and Modules

Load the relevant libraries for the federated learning code.

In [2]:
import torch

# Transferer
from transfer_attacks.Transferer import *
from transfer_attacks.Params import *

### Transfer Attack Sweeping Different Configs

In [3]:
client_idx = 0
victim_idxs = [0,1,2,3]

transferer = Transferer(filename = 'exp2_neck2_head3')
transferer.generate_advNN(client_idx = client_idx)
transferer.generate_victims(client_idxs = victim_idxs)
# transferer.ifsgm_params = IFSGM_Params()



Loading  all_data_12_niid_0_keep_0_train_9.json
Loading  all_data_20_niid_0_keep_0_train_9.json
Loading  all_data_11_niid_0_keep_0_train_9.json
Loading  all_data_18_niid_0_keep_0_train_9.json


/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))


In [9]:
transferer.generate_xadv(atk_type = "cw")
transferer.send_to_victims(victim_idxs)

In [10]:
j = 2

print("orig_acc_transfers\n",transferer.orig_acc_transfers[j])
print("orig_similarities\n",transferer.orig_similarities[j])
print("orig_target_hit\n",transferer.orig_target_hit[j])
print("adv_acc_transfers\n",transferer.adv_acc_transfers[j])
print("adv_similarities\n",transferer.adv_similarities[j])
print("adv_target_hit\n",transferer.adv_target_hit[j])

orig_acc_transfers
 tensor(0.8000, device='cuda:0')
orig_similarities
 tensor(0.8000, device='cuda:0')
orig_target_hit
 tensor(0., device='cuda:0')
adv_acc_transfers
 tensor(0.1000, device='cuda:0')
adv_similarities
 tensor(0., device='cuda:0')
adv_target_hit
 tensor(0., device='cuda:0')


In [11]:
transferer.y_true

tensor([30,  7,  2,  4, 43,  3,  2, 15,  6,  4], device='cuda:0')

In [12]:
torch.argmax(transferer.advNN(transferer.x_orig),dim=1)

tensor([30,  7,  2,  4, 43,  3,  2, 15,  6,  4], device='cuda:0')

In [13]:
torch.argmax(transferer.advNN(transferer.x_adv),dim=1)

tensor([20, 20, 20, 20, 20, 20, 20, 20, 20, 20], device='cuda:0')

In [14]:
torch.argmax(transferer.victims[2](transferer.x_adv),dim = 1)

tensor([46, 34, 34, 17, 46, 46,  4, 34, 17,  4], device='cuda:0')