# FGSM Sweep 1

TJ Kim <br/>
1/16/21

Updated <br/>
2/15/21

#### Objective: 
Run FGSM attack on different number of head layers in federated learning and observe performance,


In [4]:
cd '/home/ubuntu/FedAtk/' 

/home/ubuntu/FedAtk


### Load Relevant Libraries and Modules

Load the relevant libraries for the federated learning code.

In [5]:
import torch

# Transferer
from transfer_attacks.Transferer import *
from transfer_attacks.Params import *

### Transfer Attack Sweeping Different Configs

In [6]:
client_idx = 0
victim_idxs = [0,1,2,3]

transferer = Transferer(filename = 'exp2_neck2_head3')
transferer.generate_advNN(client_idx = client_idx)
transferer.generate_victims(client_idxs = victim_idxs)
# transferer.ifsgm_params = IFSGM_Params()



Loading  all_data_12_niid_0_keep_0_train_9.json
Loading  all_data_20_niid_0_keep_0_train_9.json
Loading  all_data_11_niid_0_keep_0_train_9.json
Loading  all_data_18_niid_0_keep_0_train_9.json


/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))


In [7]:
transferer.generate_xadv(atk_type = "fgsm")
transferer.send_to_victims(victim_idxs)

Attak type unidentified -- Running IFSGM


In [8]:
j = 2

print("orig_acc_transfers\n",transferer.orig_acc_transfers[j])
print("orig_similarities\n",transferer.orig_similarities[j])
print("orig_target_hit\n",transferer.orig_target_hit[j])
print("adv_acc_transfers\n",transferer.adv_acc_transfers[j])
print("adv_similarities\n",transferer.adv_similarities[j])
print("adv_target_hit\n",transferer.adv_target_hit[j])

orig_acc_transfers
 tensor(0.8250, device='cuda:0')
orig_similarities
 tensor(0.6830, device='cuda:0')
orig_target_hit
 tensor(0.0040, device='cuda:0')
adv_acc_transfers
 tensor(0.2210, device='cuda:0')
adv_similarities
 tensor(0.3180, device='cuda:0')
adv_target_hit
 tensor(0.3090, device='cuda:0')


In [9]:
transferer.y_true

tensor([31, 33, 27,  1,  7,  6,  5,  3,  0,  4,  6,  7,  1, 43, 40, 53,  4,  3,
         7,  3,  5,  3,  4,  8,  1,  9,  1,  2,  8,  8, 42, 25, 12, 32, 42, 51,
         7,  2,  5,  1,  9,  0,  8,  5,  0,  9,  3,  9,  6,  3,  0, 29,  9,  1,
         1,  8,  9,  3,  5,  6,  8,  2,  6,  9,  3,  0, 56, 44, 29, 30, 24, 31,
        39, 56, 36,  8,  2,  7,  9,  1,  4,  6,  0,  1,  1,  2,  3, 44, 46, 59,
        27, 15,  2,  1,  2,  4,  0,  1,  2,  3,  3,  6,  2,  7,  1,  6,  2,  5,
         8,  9,  8,  6,  0,  8,  1,  3,  9,  3, 22, 33, 30, 35, 53, 47, 16, 11,
         3,  4,  4,  9,  7,  1,  6,  4,  5,  9,  1,  5,  7,  2, 60, 51, 16, 29,
        14, 38, 49,  4,  9,  6,  6,  0,  0,  5,  3,  3,  3,  9,  1,  2,  6,  6,
         4,  7,  7,  7,  1,  8,  0,  4,  9, 34, 18, 51, 47, 47, 44, 55, 11, 16,
         1,  3,  5,  3,  8,  1,  2,  0,  7,  8, 51, 56, 47,  0,  5,  4,  4,  0,
         1,  2,  0,  6,  1,  1,  8,  1,  8,  3,  2,  5,  6,  6,  5,  1,  8,  5,
         3,  3,  1,  3,  8,  3,  9, 53, 

In [10]:
torch.argmax(transferer.advNN(transferer.x_orig),dim=1)

tensor([30, 34, 15,  1,  7,  6,  5,  3, 30,  4, 37,  7, 47, 43, 40, 53,  4,  3,
         7,  3,  5,  3,  4,  8, 47,  9, 47,  2,  8,  8, 42, 25, 12, 23, 36, 24,
         7,  2,  5, 47,  9, 24,  8,  5, 24,  9,  3,  9, 21,  3, 24, 28,  9, 18,
         1,  8,  9,  3, 28,  6,  8,  2,  6,  9,  3, 24, 30, 18, 53, 30, 24, 31,
         2, 30, 36,  8,  2, 49, 36, 18,  4,  6, 24, 18,  1,  2,  3, 18, 46, 59,
        27, 15,  2, 47,  2,  4, 24, 47,  2,  3,  3,  6,  2,  7, 47,  6,  2, 16,
         8,  9, 42,  6, 24, 11, 47,  3,  9,  3, 23, 59, 30, 35, 53, 47, 16, 24,
        59,  4,  4,  4,  7, 18, 21,  4, 28, 49, 18,  5,  7, 61,  7, 51,  6, 55,
        40, 38, 49,  4, 42,  6,  6, 24, 24, 28,  3,  3,  3,  9,  1, 61,  6,  6,
         4,  7,  7,  7, 47, 11,  0,  4, 42,  4, 18, 25, 47, 47, 43, 55, 37, 16,
        47, 42, 28, 28,  8, 47,  2, 24,  7,  8, 34, 30, 47, 30,  5,  4,  4, 24,
        18,  2, 24,  6, 47, 47,  8, 47,  8,  3,  2,  5,  6,  6,  5, 47,  8,  5,
         3,  3, 47, 28,  8, 28,  9, 53, 

In [11]:
torch.argmax(transferer.advNN(transferer.x_adv),dim=1)

tensor([15, 15, 15, 15, 15, 15, 15, 15, 38, 15, 16, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 42, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 49, 15, 15, 15, 31, 15, 15,
        31, 15, 15, 15,  0, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 42, 15, 15, 15, 15, 15, 15, 42, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15,  0, 15, 15, 15, 15, 15, 26, 33,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 60, 15, 15, 15, 15,
        30, 15, 15, 15, 15, 15, 15, 56, 15, 15, 15, 15, 15, 15, 15, 61, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 31, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 56, 15, 15, 15, 15, 15, 30,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 38, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 

In [12]:
torch.argmax(transferer.victims[2](transferer.x_adv),dim = 1)

tensor([41, 15, 15, 41, 29, 15,  5,  5,  0,  4,  4,  7, 15, 15, 15, 15,  4, 41,
         7,  5,  5, 15,  9,  8, 55,  5, 55, 41, 41, 15, 15, 15, 12,  8, 15, 15,
         7, 41, 15, 15, 41, 41,  5, 15, 41, 15,  5,  7, 41, 11, 41,  8, 15, 55,
        55,  8, 15,  8, 41,  6,  8, 15, 41, 15,  8,  0, 15, 15, 15, 30,  0, 15,
        55, 15, 15, 55,  1, 15, 15, 41,  4,  4, 15, 55, 41, 15,  5, 55, 15,  4,
        15, 15,  2, 41,  2, 15,  5, 41, 41,  3,  5, 41,  2,  7, 41,  6, 47, 15,
        41, 15,  5,  6, 15, 15, 41,  8,  9,  3, 11,  6,  5, 15, 15, 41, 16,  8,
        55,  8, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,  5, 15, 15, 15, 15,
        11, 15, 15, 15, 15, 15,  6, 60, 41, 15, 15,  5,  5, 15, 15, 61,  6, 41,
        15, 29,  8,  9, 15,  8, 41, 41,  5,  4, 29, 41, 15, 41, 15, 15, 15,  5,
        55,  5,  5,  5,  7, 41,  2,  5,  7,  8, 15, 60, 15, 41, 15, 15, 15,  0,
        15,  2, 41, 41, 41, 15,  8, 41,  8,  8, 15,  5,  6, 41,  5, 41,  8,  5,
        41, 15, 41,  8, 15,  2,  9, 15, 