# Transferability Metrics

TJ Kim <br/>
2/4/21

Updated <br/>
2/21/21

#### Objective: 
To the existing (and functioning) FGSM attack, add measurements of transferability between different networks.
This will help us compare as well. 

#### Transferability Metrics
- Size of input gradient
- Gradient Alignment
- Variance of Loss

#### Other Metrics
- Confidence of attack (Loss towards target)
- L2 Distance from original point


In [1]:
cd '/home/ubuntu/FedAtk/' 

### Load Relevant Libraries and Modules

Load the relevant libraries for the federated learning code.

In [2]:
import torch

# Personal NN
# from transfer_attacks.Personalized_NN import *
from transfer_attacks.Transferer import *
# Import the Rest

### Load and Run the System

In [3]:
client_idx = 0
victim_idxs = [0,1,2,3,4,5,6,7]

# Generate NN and Victims
transferer = Transferer(filename = 'exp4_neck2_0_head3')
transferer.generate_advNN(client_idx = client_idx)
transferer.generate_victims(client_idxs = victim_idxs)

Loading  all_data_12_niid_0_keep_0_train_9.json
Loading  all_data_20_niid_0_keep_0_train_9.json
Loading  all_data_11_niid_0_keep_0_train_9.json
Loading  all_data_18_niid_0_keep_0_train_9.json


/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))


In [4]:
transferer.generate_xadv(atk_type = "ifsgm")
transferer.send_to_victims(victim_idxs)

In [5]:
# Run the empirical metrics
transferer.check_empirical_metrics(orig_flag = True, batch_size = 100)
#print(transferer.metric_variance)
#print(transferer.metric_ingrad)
print(transferer.metric_alignment[3])

tensor(1.0058)


In [6]:
for i in range(8):
    print(torch.argmax(transferer.victims[i](transferer.x_orig),dim=1))

tensor([ 4,  3, 48, 55,  4, 25, 61, 53,  5, 53,  5,  7,  5,  1,  7,  1, 59, 24,
         5, 12, 34,  6,  7, 24, 28, 43,  9, 53,  9, 30, 55,  5, 49, 51,  7,  2,
         8,  4, 28,  5, 53, 55,  0, 43,  5,  0,  0, 14,  5,  0,  5,  9, 23, 39,
         5,  9, 30, 53,  6, 49,  8, 34,  9, 40, 28,  3,  1,  7,  6,  3,  3, 23,
         0,  6, 28,  3, 15,  1,  4, 54,  3,  3, 23,  1, 39,  7, 49,  2,  1,  6,
         4,  8, 28, 18,  0, 37, 12, 28,  3, 47, 34, 30, 30, 39,  2,  2, 34,  9,
         8, 30,  1,  0, 26,  3, 31, 29, 22,  4,  0,  1, 12, 37,  0,  7, 12, 24,
         4,  1,  3, 40, 34,  8, 11, 52,  6,  6, 61,  6,  5,  9,  1, 43, 31, 25,
         2,  9,  8,  9,  6,  0,  6,  1,  4,  4,  3, 16,  2, 47,  9,  4,  7,  8,
         9,  0,  3, 12,  9, 23,  9, 18,  7, 39,  2,  1,  0, 10,  2,  9,  8, 31,
        29,  6,  3,  3,  4,  7,  2, 49,  2, 61,  9, 55,  8, 30,  1,  2,  4,  9,
        28, 25, 42, 12,  1,  3, 49, 34, 12, 18,  5,  4, 22,  5, 40, 28, 30, 50,
        10,  2, 39, 34, 36,  7,  6,  3, 

tensor([ 4,  3, 48, 55,  4, 25,  2, 53,  5, 53,  5,  7,  5,  1,  7,  1, 59,  0,
         5, 12,  4,  6,  7,  0,  5, 43,  9, 53,  9, 56, 55,  5, 49, 51,  7,  2,
         8,  4,  5,  5, 53, 47,  0, 46,  5,  0,  0,  8,  5,  0,  5, 15, 58, 39,
         5,  9, 35, 53,  6, 49,  8, 33,  9, 40,  3,  3,  1,  7,  6,  3,  3, 49,
         0, 16, 28, 42, 41,  1,  4, 54,  3,  3, 36,  1, 39,  7, 49,  2,  1,  6,
         4,  8, 54,  1, 13,  6, 38,  3,  3, 47,  9, 30,  4, 39,  2,  2, 60,  9,
         8, 30, 47,  0, 26,  3, 57,  7, 26,  4,  0,  1, 38, 43,  0,  7, 12, 56,
         4,  1,  3, 40, 60,  8, 11, 52,  6,  6,  2,  6,  5,  9,  1, 43, 31, 25,
         2,  9,  8,  9,  6,  0,  6,  1,  4,  4,  3, 16,  2,  1,  9,  4,  7,  8,
         9,  0,  3, 38,  8, 48,  9,  1,  7, 39,  2,  1,  0, 10,  2,  9,  8,  4,
        29,  6,  3,  3,  4,  7,  2, 49,  2, 61,  9, 55,  8, 10,  1,  2,  4,  9,
        28, 25,  9, 12, 18,  3, 49, 39, 38,  1,  5,  4, 22,  5, 40,  5, 32, 40,
        10,  2, 39, 34, 36,  7,  6,  3, 

tensor([ 4,  3, 48, 55,  4, 25,  2, 53,  5, 53, 28,  7,  5,  1,  7,  1, 59, 24,
         5, 12,  4,  6,  7,  0, 28, 20,  9, 53,  9, 56, 55,  5, 49, 51,  7,  2,
         8,  4,  5,  5, 53, 21,  0, 37,  8,  0,  0, 14,  5,  0,  5, 34, 23, 39,
         5,  9, 39, 53,  6, 49,  8, 33,  9, 40, 28,  3,  1,  7,  6,  3,  3, 23,
         0,  6, 28,  3, 41,  1,  4, 54,  3,  3, 23,  1, 39,  7, 49,  2,  1,  6,
         4,  8, 28,  1, 13, 37, 12,  0,  3, 47,  9, 30, 30, 39,  2,  2, 60,  9,
         8, 30,  1, 50, 26,  3, 57,  7, 24,  4,  0,  1, 40, 37,  0,  7, 12,  6,
         4,  1,  3, 40, 34,  8,  8, 52,  6,  6, 61,  6,  5,  9,  1, 43, 31, 25,
         2,  9,  8,  9,  6,  0,  6,  1,  4,  4,  3, 16,  2,  1,  9,  4,  7,  8,
         9,  0,  3, 38,  8, 23,  9,  1,  7, 39,  2,  1,  0, 10,  2,  9,  8, 31,
        29,  6,  3,  3,  4,  7,  2, 49,  2, 61,  9, 55,  8, 48,  1,  2,  4,  9,
         5, 25,  9, 12,  1,  3, 49, 39, 12,  1,  5,  4, 22,  5, 40, 28, 30,  0,
        10,  2, 39, 34,  2,  7,  8,  3, 

In [7]:
for i in range(8):
    print(torch.argmax(transferer.victims[i](transferer.x_adv),dim=1))

tensor([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 

tensor([20, 20, 22, 20, 20, 20, 20, 20, 20, 20,  5, 20,  5, 20, 15, 20, 20, 11,
        15, 20,  4, 20, 33, 20,  5, 20, 20, 20,  4, 20, 20, 20, 20, 20, 27, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 27, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 27, 20, 20, 15, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 19, 20, 20, 20, 27, 15, 20, 27, 20, 20,
        20, 20, 33, 24, 20, 20, 20, 20, 20, 20, 23, 27, 20, 20, 20, 20, 24, 20,
        20, 20, 20, 27, 20, 20, 20, 20, 23, 20, 20, 20, 20, 20, 20, 15, 20, 20,
         4, 20, 20, 20, 20, 20, 20, 42, 27, 20, 20, 20, 15, 20, 20, 20, 20, 20,
        15, 20, 20, 20, 20,  0, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20,  0, 20, 20, 20, 20, 20, 20, 20, 27, 20, 20,  4, 20, 20, 20, 20,
        15, 20, 20, 20, 20, 20, 20, 20, 27, 15, 34, 24, 20, 20, 20, 20, 20,  4,
        20, 20, 20, 15, 20, 15, 20, 17, 20, 20, 20, 17, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 33, 20, 20, 

tensor([20, 11, 22, 20, 20, 20, 20, 20,  5, 20, 20, 20, 28, 20, 20, 20, 20, 11,
        20, 20,  4, 20, 27, 27,  5, 20, 20, 20, 20, 27, 20, 20, 20, 15, 20, 27,
        20, 20, 11, 20, 20, 20, 20, 20, 20, 20, 22, 20,  5, 20, 20, 15, 20, 20,
         5, 20, 20, 20, 20, 20, 27, 20, 27, 20, 20, 20, 20, 27, 20, 20, 20, 20,
        20, 27, 11, 27, 20, 20, 20, 20, 27, 15, 10, 20, 20, 15, 20, 27, 20, 20,
         4, 20, 27, 20, 20, 20, 20, 20, 20, 20, 11, 11, 20, 20, 20, 27, 20, 20,
        27, 20, 20, 27, 27, 11, 20, 20, 20, 20, 27, 20, 20, 20, 27, 27, 20, 15,
        20, 20, 20, 20, 20, 20, 20, 22, 20, 20, 27, 20, 20, 27, 20, 20, 20, 20,
        20, 27, 27, 15, 20,  0, 20, 20, 17, 20, 27, 20, 20, 20, 27, 20, 20, 27,
        27, 20,  3, 20, 27, 20, 27, 20, 20, 20, 27, 20, 20, 17, 20, 20, 27, 20,
        20, 20, 20, 20, 20, 27, 27, 20, 27, 20, 17, 20, 20, 27, 20, 20, 20, 20,
        20, 20, 20, 20, 27, 27, 20, 11, 20, 20, 20, 17, 27, 11, 20, 20, 27, 20,
        20, 20, 20, 20, 20, 20, 20, 27, 

tensor([20, 27, 48, 20, 20, 20, 20, 20, 20, 20, 20, 20,  5, 20, 20, 20, 20, 20,
        20, 20,  4, 20, 20, 23, 20, 20, 20, 20,  4, 20, 20, 20, 20, 20, 27, 20,
        20, 20, 20, 20, 20, 20,  3, 20, 20, 20, 20, 20, 20, 20, 20, 15, 20, 20,
         5, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,  5,  3, 20,  4, 20, 20, 20,
        20, 20,  5, 20, 15, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 27, 20, 20,
        20, 20, 27, 20, 20, 20, 20, 20, 20, 15, 27, 20, 20, 20, 20, 27, 20, 20,
        20, 20, 55, 20, 20, 20,  3, 20, 20, 20, 20, 20, 20, 20, 20, 15, 20, 20,
         4, 20, 20, 20, 20, 20, 20,  4, 15, 20, 20, 20, 20, 20, 15, 20,  3, 20,
        27, 20, 15, 20, 20,  0, 20, 20, 20, 20, 27, 16, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 15, 20, 20,  4, 27,  4, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 27, 20, 20, 20, 20, 20,  3, 20, 20,  4,
        20, 20, 20, 20, 15, 15, 20, 30, 20, 20, 20,  4, 22,  5, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 

In [8]:
for j in range(8):
    print("\n NN", j)
    print("orig_acc_transfers: ",transferer.orig_acc_transfers[j])
    print("orig_similarities: ",transferer.orig_similarities[j])
    print("orig_target_hit:",transferer.orig_target_hit[j])
    print("adv_acc_transfers:",transferer.adv_acc_transfers[j])
    print("adv_similarities:",transferer.adv_similarities[j])
    print("adv_target_hit:",transferer.adv_target_hit[j])
    print(transferer.metric_alignment[j])


 NN 0
orig_acc_transfers:  tensor(0.8880, device='cuda:0')
orig_similarities:  tensor(1., device='cuda:0')
orig_target_hit: tensor(0.0020, device='cuda:0')
adv_acc_transfers: tensor(0.0030, device='cuda:0')
adv_similarities: tensor(1., device='cuda:0')
adv_target_hit: tensor(0.9990, device='cuda:0')
tensor(0.)

 NN 1
orig_acc_transfers:  tensor(0.7960, device='cuda:0')
orig_similarities:  tensor(0.8320, device='cuda:0')
orig_target_hit: tensor(0.0010, device='cuda:0')
adv_acc_transfers: tensor(0.0440, device='cuda:0')
adv_similarities: tensor(0.3390, device='cuda:0')
adv_target_hit: tensor(0.3390, device='cuda:0')
tensor(1.0839)

 NN 2
orig_acc_transfers:  tensor(0.7770, device='cuda:0')
orig_similarities:  tensor(0.8020, device='cuda:0')
orig_target_hit: tensor(0.0070, device='cuda:0')
adv_acc_transfers: tensor(0.0270, device='cuda:0')
adv_similarities: tensor(0.7580, device='cuda:0')
adv_target_hit: tensor(0.7580, device='cuda:0')
tensor(1.1412)

 NN 3
orig_acc_transfers:  tensor(0.