# CW Attack Test

TJ Kim <br/>
2/2/21

Updated <br/>
2/18/21

#### Objective: 
Run CW Attack on generic federated learning setting.
See what the transfer rate is.

The goal is to build an infrastructure of C&W Attack Implementation.


In [1]:
cd '/home/ubuntu/FedAtk/' 

/home/ubuntu/FedAtk


### Load Relevant Libraries and Modules

Load the relevant libraries for the federated learning code.

In [2]:
# Transferer
from transfer_attacks.Transferer import *
import torch

### Directly Make victim NN Class

### Transfer Attack For Set Configuration

As a demo, we will perform a transfer attack from client 0 to the other 7 clients in the system. The implementation is identical to the FGSM testbed.

In [3]:
client_idx = 0
victim_idxs = [0,1,2,3]

transferer = Transferer(filename = 'exp2_neck2_head3')
transferer.generate_advNN(client_idx = client_idx)
transferer.generate_victims(client_idxs = victim_idxs)
transferer.cw_params = CW_Params()
transferer.generate_xadv(atk_type = "cw")
transferer.send_to_victims(victim_idxs)

Loading  all_data_12_niid_0_keep_0_train_9.json
Loading  all_data_20_niid_0_keep_0_train_9.json
Loading  all_data_11_niid_0_keep_0_train_9.json
Loading  all_data_18_niid_0_keep_0_train_9.json


/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))


In [4]:
j = 2

print("orig_acc_transfers\n",transferer.orig_acc_transfers[j])
print("orig_similarities\n",transferer.orig_similarities[j])
print("orig_target_hit\n",transferer.orig_target_hit[j])
print("adv_acc_transfers\n",transferer.adv_acc_transfers[j])
print("adv_similarities\n",transferer.adv_similarities[j])
print("adv_target_hit\n",transferer.adv_target_hit[j])

orig_acc_transfers
 tensor(0.8000, device='cuda:0')
orig_similarities
 tensor(0.8000, device='cuda:0')
orig_target_hit
 tensor(0., device='cuda:0')
adv_acc_transfers
 tensor(0.1000, device='cuda:0')
adv_similarities
 tensor(0.2000, device='cuda:0')
adv_target_hit
 tensor(0.2000, device='cuda:0')


In [5]:
transferer.y_true

tensor([ 7,  3,  8,  0, 49, 17, 41,  8,  2, 20], device='cuda:0')

In [6]:
torch.argmax(transferer.victims[2](transferer.x_orig),dim=1)

tensor([ 7,  3,  8,  0, 49,  4, 41,  8,  2, 46], device='cuda:0')

In [7]:
torch.argmax(transferer.advNN(transferer.x_orig),dim=1)

tensor([ 7,  3,  8,  0, 49, 17, 41,  8,  2, 20], device='cuda:0')

In [8]:
torch.argmax(transferer.advNN(transferer.x_adv),dim=1)

tensor([20, 20, 20, 20, 20, 20, 20, 20, 20, 20], device='cuda:0')

In [9]:
torch.argmax(transferer.victims[2](transferer.x_adv),dim = 1)

tensor([34, 20, 41, 46, 34, 34, 34, 34, 34, 20], device='cuda:0')